const { default: makeWASocket, useMultiFileAuthState, delay, fetchLatestBaileysVersion } = require("@whiskeysockets/baileys");
const { GoogleGenerativeAI } = require("@google/generative-ai");
const pino = require("pino");
const express = require("express");
const app = express();
const PORT = process.env.PORT || 3000;

// Gemini AI Setup
const genAI = new GoogleGenerativeAI(process.env.API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-pro" });

let botActive = true;

app.get("/", (req, res) => res.send("DTZ AI SERVER IS LIVE! 🧟‍♂️"));

async function startDTZ() {
    const { state, saveCreds } = await useMultiFileAuthState('session_auth');
    const { version } = await fetchLatestBaileysVersion();

    const sock = makeWASocket({
        auth: state,
        version,
        logger: pino({ level: "silent" }),
        browser: ["Ubuntu", "Chrome", "20.0.04"]
    });

    // Pairing Code Request
    if (!sock.authState.creds.registered) {
        setTimeout(async () => {
            let num = "94743769118"; // <--- මෙතනට ඔයාගේ නම්බර් එක 94 දාලා ගහන්න
            let code = await sock.requestPairingCode(num);
            console.log("\n----------------------------");
            console.log("YOUR PAIRING CODE: " + code);
            console.log("----------------------------\n");
        }, 5000);
    }

    sock.ev.on("creds.update", saveCreds);

    // Connection Success Message
    sock.ev.on("connection.update", async (update) => {
        const { connection } = update;
        if (connection === "open") {
            const welcomeMsg = `*~සාර්තකව ඔබෙ DTZ AI ඇසිස්ටන් සම්බන්ද වී ඇත මෙතැන් සිට මම ඔබට සේවය කරමි ඔබට මාව ක්‍රියාත්මක කිරීමට වාගෙම අක්ක්‍රිය කිරීමට හැක ඒවෙනුවට ඔබට කරන්න තිබෙන්නෙ !on / !of යනුවෙන් සදහන් කරන්න පමනයි~* 🇦🇱🧟‍♂️`;
            await sock.sendMessage(sock.user.id, { 
                image: { url: "https://pmd-img2url.koyeb.app/v/a27c88198869bb378af7e4bc7e8bdbd6.jpg" }, 
                caption: welcomeMsg 
            });
        }
    });

    // Message Logic
    sock.ev.on("messages.upsert", async ({ messages }) => {
        const msg = messages[0];
        if (!msg.message || msg.key.fromMe) return;
        const sender = msg.key.remoteJid;
        const pushName = msg.pushName || "Friend";
        const body = msg.message.conversation || msg.message.extendedTextMessage?.text || "";

        if (body === "!on") { botActive = true; return await sock.sendMessage(sender, { text: "✅ DTZ AI ON" }); }
        if (body === "!off") { botActive = false; return await sock.sendMessage(sender, { text: "❌ DTZ AI OFF" }); }

        if (botActive) {
            try {
                const prompt = `You are DTZ AI created by Sithuwa. Reply to this message from ${pushName}: "${body}". Be friendly and natural in Sinhala/English.`;
                const result = await model.generateContent(prompt);
                const aiReply = result.response.text();

                await sock.sendPresenceUpdate('composing', sender);
                await delay(2000);
                await sock.sendMessage(sender, { text: aiReply + "\n\n_Generated by DTZ AI_ 🧟‍♂️" });
            } catch (e) { console.log("AI Error"); }
        }
    });
}

app.listen(PORT, () => {
    console.log("Server listening...");
    startDTZ();
});
